# permissions for end users to view awspcaclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/managed-by: kustomize
  name: awspcaclusterissuer-viewer-role
rules:
- apiGroups:
  - awspca.cert-manager.io
  resources:
  - awspcaclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awspca.cert-manager.io
  resources:
  - awspcaclusterissuers/status
  verbs:
  - get
